#ifndef BABA_IS_YOU_ENTITY_NAME_AND_TYPE_H
#define BABA_IS_YOU_ENTITY_NAME_AND_TYPE_H


enum class EntityType
{
	CHARACTER = 0,
	DIRECTIONAL,
	STATIC,
	TEXT,
	NONE
};
static const char* entity_type_str[] = { "character", "directional", "static", "text" };

static struct NameAndType
{
	const char* name;
	EntityType type;
}name_and_type[] = {
{"ALGAE",EntityType::NONE},
{"ALL",EntityType::NONE},
{"ANNI",EntityType::NONE},
{"BABA",EntityType::CHARACTER },
{"BAT",EntityType::NONE},
{"BELT",EntityType::NONE },
{"BIRD",EntityType::DIRECTIONAL  },
{"BOG",EntityType::NONE},
{"BOLT",EntityType::DIRECTIONAL  },
{"BOX",EntityType::STATIC  },
{"BRICK",EntityType::NONE},
{"BUBBLE",EntityType::NONE },
{"BUG",EntityType::DIRECTIONAL  },
{"CAKE",EntityType::NONE},
{"CASH",EntityType::NONE},
{"CIRCLE",EntityType::NONE  },
{"CLIFF",EntityType::NONE },
{"CLOUD",EntityType::NONE },
{"COG",EntityType::DIRECTIONAL  },
{"CRAB",EntityType::DIRECTIONAL  },
{"CRYSTAL",EntityType::NONE},
{"CUP",EntityType::NONE},
{"CURSOR",EntityType::NONE},
{"DOOR",EntityType::STATIC  },
{"DOT",EntityType::NONE},
{"DUST",EntityType::NONE },
{"EMPTY",EntityType::NONE  },
{"EYE",EntityType::NONE},
{"FENCE",EntityType::NONE  },
{"FIRE",EntityType::NONE },
{"FLAG",EntityType::STATIC  },
{"FLOWER",EntityType::NONE},
{"FOLIAGE",EntityType::NONE },
{"FOOT",EntityType::NONE},
{"FRUIT",EntityType::NONE },
{"FUNGI",EntityType::NONE },
{"FUNGUS",EntityType::NONE  },
{"GEM",EntityType::NONE},
{"GHOST",EntityType::DIRECTIONAL  },
{"GRASS",EntityType::STATIC  },
{"GROUP",EntityType::NONE },
{"HAND",EntityType::NONE},
{"HEDGE",EntityType::STATIC  },
{"HUSK",EntityType::NONE },
{"HUSKS",EntityType::NONE  },
{"ICE",EntityType::NONE},
{"IMAGE",EntityType::NONE  },
{"JELLY",EntityType::STATIC  },
{"KEKE",EntityType::CHARACTER  },
{"KEY",EntityType::STATIC  },
{"LADDER",EntityType::NONE  },
{"LAVA",EntityType::STATIC  },
{"LEAF",EntityType::NONE},
{"LEVEL",EntityType::NONE },
{"LINE",EntityType::NONE},
{"LOVE",EntityType::STATIC  },
{"ME",EntityType::CHARACTER  },
{"MOON",EntityType::NONE },
{"ORB",EntityType::NONE},
{"PILLAR",EntityType::STATIC  },
{"PIPE",EntityType::NONE},
{"REED",EntityType::NONE},
{"ROBOT",EntityType::CHARACTER  },
{"ROCK",EntityType::STATIC  },
{"ROCKET",EntityType::DIRECTIONAL  },
{"ROSE",EntityType::NONE},
{"RUBBLE",EntityType::NONE  },
{"SHIRT",EntityType::NONE },
{"SIGN",EntityType::NONE},
{"SKULL",EntityType::DIRECTIONAL  },
{"SPIKE",EntityType::NONE},
{"SQUARE",EntityType::NONE },
{"STAR",EntityType::STATIC  },
{"STATUE",EntityType::NONE  },
{"STUMP",EntityType::NONE },
{"SUN",EntityType::NONE},
{"TEXT",EntityType::NONE },
{"TILE",EntityType::NONE },
{"TRACK",EntityType::NONE  },
{"TRAIN",EntityType::NONE  },
{"TREE",EntityType::NONE },
{"TREES",EntityType::NONE  },
{"TRIANGLE",EntityType::NONE  },
{"UFO",EntityType::NONE},
{"WALL",EntityType::STATIC  },
{"WATER",EntityType::STATIC  },
{"WORM",EntityType::NONE  },
{"A",EntityType::NONE },
{"B",EntityType::NONE },
{"C",EntityType::NONE },
{"D",EntityType::NONE },
{"E",EntityType::NONE },
{"F",EntityType::NONE },
{"G",EntityType::NONE },
{"H",EntityType::NONE },
{"I",EntityType::NONE },
{"J",EntityType::NONE },
{"K",EntityType::NONE },
{"L",EntityType::NONE },
{"M",EntityType::NONE },
{"N",EntityType::NONE },
{"O",EntityType::NONE },
{"P",EntityType::NONE },
{"Q",EntityType::NONE },
{"R",EntityType::NONE },
{"S",EntityType::NONE },
{"T",EntityType::NONE },
{"U",EntityType::NONE },
{"V",EntityType::NONE },
{"W",EntityType::NONE },
{"X",EntityType::NONE },
{"Y",EntityType::NONE },
{"Z",EntityType::NONE }
};

#endif // !BABA_IS_YOU_ENTITY_NAME_AND_TYPE_H